[[main]]
    identifier = "home"
    name = "Home"
    url = "/en/"
    weight = 1

[[main]]
    identifier = "post"
    name = "Posts"
    url = "/en/posts"
    weight = 2

[[main]]
    identifier = "about"
    name = "About"
    url = "/en/about"
    weight = 3

[[main]]
    identifier = "categories"
    name = "Categories"
    url = "/en/categories"
    weight = 4

[[main]]
    identifier = "tags"
    name = "Tags"
    url = "/en/tags"
    weight = 5

[[main]]
    identifier = "donate"
    name = "Donate"
    url = "https://ko-fi.com/hlc23"
    weight = 6
