# Homepage Config
isSinglePage = true

# Meta Config
description = "Hello"

# Header Configuration
avatar = "img/avatar.jpg"

#favicon
favicon = "icons/favicon.ico"

# disqus is a comment system. see https://disqus.com
disqusShortname = ""

[emoji]
enableEmoji = true

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        title = true

# giscus is a comment system based on GitHub Discussions. see https://giscus.app
[giscus]       
    enable = false
    repo = ""
    repoId = ""
    category = "Announcements"
    categoryId = ""
    # mapping = "pathname"  # comment value is the default value
    # strict = 0
    # reactionsEnabled = 1
    # emitMetadata = 0
    # inputPosition = "top"
    # theme = "light"
    # lang = "zh-CN"
    # lazyLoading = true